### ISSUE TITLE
Удваиваются элементы в списке __data, класса Rates

### ISSUE THREAD

**Issue by Hibios** [maksam07/bestchange_api#2]
При подобной структуре кода:

api = BestChange(cache=False)
rates = api.rates()

Если используем фильтры в цикле много раз, то в классе Rates увеличивается список __data, фильтры замедляются.
br = rates.filter(..., ...)
sr = rates.filter(..., ...)

Переместил переменную класса __data в __init__ контруктор:

class Rates:
    def __init__(self, text, split_reviews):
        self.__data = []
        for row in text.splitlines():
.......

Теперь всё стало ок, посмотри как сможешь и исправь с тестами

**Comment by maksam07** [comment]
Воспроизвести проблему не смог, но допустим вариант решения имеет место быть. Немного подправил, библиотеку выгрузил, можно обновляться
