### ISSUE TITLE
На ubuntu при выключенном параметре cache забивается /tmp каталог

### ISSUE THREAD

**Issue by Hibios** [maksam07/bestchange_api#3]
На ubuntu при выключенном параметре cache /tmp каталог забивается файлами из метода load и названием filename, прошу добавить os.remove(filename) в конец метода в соответствии с __cache, а также зкрывать файлы по типу:
`with zipfile.open(self.__file_rates) as f:
     with TextIOWrapper(f, encoding=self.__enc) as r:
         self.__rates = Rates(r.read(), self.__split_reviews)`

**Comment by maksam07** [comment]
Предложение воплощено в жизнь. Если еще актуально использование оригинальной библиотеки - радости прошу.
