### ISSUE TITLE
URL open Error с 2 января 24 года

### ISSUE THREAD

**Issue by yuramayer** [maksam07/bestchange_api#7]
При инициализации объекта `BestChange()` возникает ошибка: `'<urlopen error [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение>'`

Ошибка появилась со 2 января, 11:15 по Мск

**Comment by maksam07** [comment]
Проверю в течение недели.

**Comment by maksam07** [comment]
> При инициализации объекта `BestChange()` возникает ошибка: `'<urlopen error [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение>'`
> 
> Ошибка появилась со 2 января, 11:15 по Мск

В BC мне ответили, что нужно использовать ссылку без ssl, а значит в класс передаем ```ssl=False```
По-умолчанию установлено True, потому что хоть и не по защищенному соединению, но с S, архив качался за пару секунд. Сейчас, кажется, он и без S качается за пару секунд.
Оперативного обновления библиотеки не ожидается, т.к. проблема быстро решается. 
Текущую проблему оставлю открытой, чтобы другие пользователи видели решение. Закрою, когда произведу все необходимые обновления.

**Comment by maksam07** [comment]
Duplicate of #6
